// This file is part of the ManagedStrings project and repository.
// Project files are licensed under the MIT license.
// https://github.com/FranciscoNabas/ManagedStrings

namespace ManagedStrings.Decoders;

// This file was auto-generated by the 'GetCharInfoData.ps1' script under the 'Tools' folder.
// PLEASE DO NOT MODIFY BY HAND!

/// <summary>
/// Static members representing the Unicode blocks.
/// This is used to determine with characters are printed.
/// It's generated from all the current <see cref="UnicodeRange"/> in <see cref="UnicodeRanges">.
/// </summary>
/// <seealso href="https://en.wikipedia.org/wiki/List_of_Unicode_characters">List of Unicode characters</seealso>
/// <seealso href="https://learn.microsoft.com/dotnet/api/system.text.unicode.unicoderanges">UnicodeRanges Class</seealso>
/// <seealso href="https://learn.microsoft.com/dotnet/api/system.text.unicode.unicoderange">UnicodeRange Class</seealso>
/// <runtimefile>src/libraries/System.Text.Encodings.Web/src/System/Text/Unicode/UnicodeRanges.generated.cs</runtimefile>
internal sealed partial class UnicodeBlocks
{
    internal static UnicodeBlock BasicLatin                          { get; } = new FriendUnicodeBlock(0x00);
    internal static UnicodeBlock LatinExtensions                     { get; } = new FriendUnicodeBlock(0x01);
    internal static UnicodeBlock AlphabeticPresentationForms         { get; } = new FriendUnicodeBlock(0x02);
    internal static UnicodeBlock Arabic                              { get; } = new FriendUnicodeBlock(0x03);
    internal static UnicodeBlock Armenian                            { get; } = new FriendUnicodeBlock(0x04);
    internal static UnicodeBlock Arrows                              { get; } = new FriendUnicodeBlock(0x05);
    internal static UnicodeBlock Balinese                            { get; } = new FriendUnicodeBlock(0x06);
    internal static UnicodeBlock Bamum                               { get; } = new FriendUnicodeBlock(0x07);
    internal static UnicodeBlock Batak                               { get; } = new FriendUnicodeBlock(0x08);
    internal static UnicodeBlock Bengali                             { get; } = new FriendUnicodeBlock(0x09);
    internal static UnicodeBlock BlockElements                       { get; } = new FriendUnicodeBlock(0x0A);
    internal static UnicodeBlock Bopomofo                            { get; } = new FriendUnicodeBlock(0x0B);
    internal static UnicodeBlock BoxDrawing                          { get; } = new FriendUnicodeBlock(0x0C);
    internal static UnicodeBlock BraillePatterns                     { get; } = new FriendUnicodeBlock(0x0D);
    internal static UnicodeBlock Buginese                            { get; } = new FriendUnicodeBlock(0x0E);
    internal static UnicodeBlock Buhid                               { get; } = new FriendUnicodeBlock(0x0F);
    internal static UnicodeBlock Cham                                { get; } = new FriendUnicodeBlock(0x10);
    internal static UnicodeBlock Cherokee                            { get; } = new FriendUnicodeBlock(0x11);
    internal static UnicodeBlock Cjk                                 { get; } = new FriendUnicodeBlock(0x12);
    internal static UnicodeBlock CombiningDiacriticalMarks           { get; } = new FriendUnicodeBlock(0x13);
    internal static UnicodeBlock CombiningHalfMarks                  { get; } = new FriendUnicodeBlock(0x14);
    internal static UnicodeBlock CommonIndicNumberForms              { get; } = new FriendUnicodeBlock(0x15);
    internal static UnicodeBlock ControlPictures                     { get; } = new FriendUnicodeBlock(0x16);
    internal static UnicodeBlock Coptic                              { get; } = new FriendUnicodeBlock(0x17);
    internal static UnicodeBlock CurrencySymbols                     { get; } = new FriendUnicodeBlock(0x18);
    internal static UnicodeBlock Cyrillic                            { get; } = new FriendUnicodeBlock(0x19);
    internal static UnicodeBlock Devanagari                          { get; } = new FriendUnicodeBlock(0x1A);
    internal static UnicodeBlock Dingbats                            { get; } = new FriendUnicodeBlock(0x1B);
    internal static UnicodeBlock EnclosedAlphanumerics               { get; } = new FriendUnicodeBlock(0x1C);
    internal static UnicodeBlock EnclosedCjkLettersandMonths         { get; } = new FriendUnicodeBlock(0x1D);
    internal static UnicodeBlock Ethiopic                            { get; } = new FriendUnicodeBlock(0x1E);
    internal static UnicodeBlock GeneralPunctuation                  { get; } = new FriendUnicodeBlock(0x1F);
    internal static UnicodeBlock GeometricShapes                     { get; } = new FriendUnicodeBlock(0x20);
    internal static UnicodeBlock Georgian                            { get; } = new FriendUnicodeBlock(0x21);
    internal static UnicodeBlock Glagolitic                          { get; } = new FriendUnicodeBlock(0x22);
    internal static UnicodeBlock GreekandCoptic                      { get; } = new FriendUnicodeBlock(0x23);
    internal static UnicodeBlock Gujarati                            { get; } = new FriendUnicodeBlock(0x24);
    internal static UnicodeBlock Gurmukhi                            { get; } = new FriendUnicodeBlock(0x25);
    internal static UnicodeBlock HalfwidthandFullwidthForms          { get; } = new FriendUnicodeBlock(0x26);
    internal static UnicodeBlock Hangul                              { get; } = new FriendUnicodeBlock(0x27);
    internal static UnicodeBlock Hanunoo                             { get; } = new FriendUnicodeBlock(0x28);
    internal static UnicodeBlock Hebrew                              { get; } = new FriendUnicodeBlock(0x29);
    internal static UnicodeBlock Hiragana                            { get; } = new FriendUnicodeBlock(0x2A);
    internal static UnicodeBlock IdeographicDescriptionCharacters    { get; } = new FriendUnicodeBlock(0x2B);
    internal static UnicodeBlock IpaExtensions                       { get; } = new FriendUnicodeBlock(0x2C);
    internal static UnicodeBlock Javanese                            { get; } = new FriendUnicodeBlock(0x2D);
    internal static UnicodeBlock Kanbun                              { get; } = new FriendUnicodeBlock(0x2E);
    internal static UnicodeBlock KangxiRadicals                      { get; } = new FriendUnicodeBlock(0x2F);
    internal static UnicodeBlock Kannada                             { get; } = new FriendUnicodeBlock(0x30);
    internal static UnicodeBlock Katakana                            { get; } = new FriendUnicodeBlock(0x31);
    internal static UnicodeBlock KayahLi                             { get; } = new FriendUnicodeBlock(0x32);
    internal static UnicodeBlock Khmer                               { get; } = new FriendUnicodeBlock(0x33);
    internal static UnicodeBlock Lao                                 { get; } = new FriendUnicodeBlock(0x34);
    internal static UnicodeBlock Lepcha                              { get; } = new FriendUnicodeBlock(0x35);
    internal static UnicodeBlock LetterlikeSymbols                   { get; } = new FriendUnicodeBlock(0x36);
    internal static UnicodeBlock Limbu                               { get; } = new FriendUnicodeBlock(0x37);
    internal static UnicodeBlock Lisu                                { get; } = new FriendUnicodeBlock(0x38);
    internal static UnicodeBlock Malayalam                           { get; } = new FriendUnicodeBlock(0x39);
    internal static UnicodeBlock Mandaic                             { get; } = new FriendUnicodeBlock(0x3A);
    internal static UnicodeBlock MathematicalOperators               { get; } = new FriendUnicodeBlock(0x3B);
    internal static UnicodeBlock MeeteiMayek                         { get; } = new FriendUnicodeBlock(0x3C);
    internal static UnicodeBlock MeeteiMayekExtensions               { get; } = new FriendUnicodeBlock(0x3D);
    internal static UnicodeBlock Miscellaneous                       { get; } = new FriendUnicodeBlock(0x3E);
    internal static UnicodeBlock ModifierToneLetters                 { get; } = new FriendUnicodeBlock(0x3F);
    internal static UnicodeBlock Mongolian                           { get; } = new FriendUnicodeBlock(0x40);
    internal static UnicodeBlock Myanmar                             { get; } = new FriendUnicodeBlock(0x41);
    internal static UnicodeBlock NewTaiLue                           { get; } = new FriendUnicodeBlock(0x42);
    internal static UnicodeBlock NKo                                 { get; } = new FriendUnicodeBlock(0x43);
    internal static UnicodeBlock NumberForms                         { get; } = new FriendUnicodeBlock(0x44);
    internal static UnicodeBlock Ogham                               { get; } = new FriendUnicodeBlock(0x45);
    internal static UnicodeBlock OlChiki                             { get; } = new FriendUnicodeBlock(0x46);
    internal static UnicodeBlock OpticalCharacterRecognition         { get; } = new FriendUnicodeBlock(0x47);
    internal static UnicodeBlock Oriya                               { get; } = new FriendUnicodeBlock(0x48);
    internal static UnicodeBlock Phagspa                             { get; } = new FriendUnicodeBlock(0x49);
    internal static UnicodeBlock PhoneticExtensions                  { get; } = new FriendUnicodeBlock(0x4A);
    internal static UnicodeBlock Rejang                              { get; } = new FriendUnicodeBlock(0x4B);
    internal static UnicodeBlock Runic                               { get; } = new FriendUnicodeBlock(0x4C);
    internal static UnicodeBlock Samaritan                           { get; } = new FriendUnicodeBlock(0x4D);
    internal static UnicodeBlock Saurashtra                          { get; } = new FriendUnicodeBlock(0x4E);
    internal static UnicodeBlock Sinhala                             { get; } = new FriendUnicodeBlock(0x4F);
    internal static UnicodeBlock SmallFormVariants                   { get; } = new FriendUnicodeBlock(0x50);
    internal static UnicodeBlock SpacingModifierLetters              { get; } = new FriendUnicodeBlock(0x51);
    internal static UnicodeBlock Specials                            { get; } = new FriendUnicodeBlock(0x52);
    internal static UnicodeBlock Sundanese                           { get; } = new FriendUnicodeBlock(0x53);
    internal static UnicodeBlock SuperscriptsandSubscripts           { get; } = new FriendUnicodeBlock(0x54);
    internal static UnicodeBlock Supplemental                        { get; } = new FriendUnicodeBlock(0x55);
    internal static UnicodeBlock SylotiNagri                         { get; } = new FriendUnicodeBlock(0x56);
    internal static UnicodeBlock Syriac                              { get; } = new FriendUnicodeBlock(0x57);
    internal static UnicodeBlock Tagalog                             { get; } = new FriendUnicodeBlock(0x58);
    internal static UnicodeBlock Tagbanwa                            { get; } = new FriendUnicodeBlock(0x59);
    internal static UnicodeBlock TaiLe                               { get; } = new FriendUnicodeBlock(0x5A);
    internal static UnicodeBlock TaiTham                             { get; } = new FriendUnicodeBlock(0x5B);
    internal static UnicodeBlock TaiViet                             { get; } = new FriendUnicodeBlock(0x5C);
    internal static UnicodeBlock Tamil                               { get; } = new FriendUnicodeBlock(0x5D);
    internal static UnicodeBlock Telugu                              { get; } = new FriendUnicodeBlock(0x5E);
    internal static UnicodeBlock Thaana                              { get; } = new FriendUnicodeBlock(0x5F);
    internal static UnicodeBlock Thai                                { get; } = new FriendUnicodeBlock(0x60);
    internal static UnicodeBlock Tibetan                             { get; } = new FriendUnicodeBlock(0x61);
    internal static UnicodeBlock Tifinagh                            { get; } = new FriendUnicodeBlock(0x62);
    internal static UnicodeBlock UnifiedCanadianAboriginalSyllabics  { get; } = new FriendUnicodeBlock(0x63);
    internal static UnicodeBlock Vai                                 { get; } = new FriendUnicodeBlock(0x64);
    internal static UnicodeBlock VariationSelectors                  { get; } = new FriendUnicodeBlock(0x65);
    internal static UnicodeBlock VedicExtensions                     { get; } = new FriendUnicodeBlock(0x66);
    internal static UnicodeBlock VerticalForms                       { get; } = new FriendUnicodeBlock(0x67);
    internal static UnicodeBlock YijingHexagramSymbols               { get; } = new FriendUnicodeBlock(0x68);
    internal static UnicodeBlock Yi                                  { get; } = new FriendUnicodeBlock(0x69);
    internal static UnicodeBlock All                                 { get; } = new FriendUnicodeBlock(0xFE);
}